name: Retrieve

on:
  workflow_dispatch:
  # schedule:
    # - cron: "0 0 * * 6" # Run the job every week on Saturday

jobs:
  update_posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub markdownify telethon
          ls -la

      - name: Create requirements.txt
        run: |
          pip freeze > requirements.txt

      - name: Upload modified file
        uses: actions/upload-artifact@v4
        with:
          name: requirements.txt
          path: requirements.txt