name: Retrieve

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run the job daily

jobs:
  update_posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot requests PyGithub markdownify

      - name: Run script
        run: |
          python .pie/script.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ secrets.GH_REPO }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
